[env:yd-esp32-s3]
platform = espressif32
board = yd-esp32-s3
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_MISO=-1
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=8
    -DTFT_RST=9
    -DLOAD_GLCD=1
    -DSPI_FREQUENCY=80000000

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/livekit/client-sdk-esp32

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
